C************************************************
C          SUPER FAST RAY TRACING FOR LIGHTBOX
C          CAN EASILY DI ARRAYS, RACKS,ETC.
C
C                CODE BY T. ZOHDI
C************************************************
Cffmpeg -i LIGHTBOX-SIM-ZOHDI.mp4 -acodec copy -vcodec copy -f mov LIGHTBOX-SIM-ZOHDI.mov

        IMPLICIT NONE

        INTEGER I,NTARGETSX1,NTARGETSX2,NTARGETSX3,COUNT,NTARGETS
        INTEGER IR,NVOXELX1,NVOXELX2,NVOXELX3,IRNUM,MOVIE
        INTEGER RANDSEED,REFLECTIONS,I1,I2,I3,IKEY
        DOUBLE PRECISION X1,X2,X3
        DOUBLE PRECISION TARDELTAX1,TARDELTAX2,TARDELTAX3,SUM
        DOUBLE PRECISION TARGETX1(1000),TARGETX2(1000),TARGETX3(1000)
        DOUBLE PRECISION TARGETRADIUSX1(1000),TARGETRADIUSX2(1000)
     $,TARGETRADIUSX3(1000),CONDITION(1000),TARGETABSORB(1000)
        DOUBLE PRECISION PX1(1000),PX2(1000),PX3(1000)
        DOUBLE PRECISION DELTAX1,DELTAX2,DELTAX3
        DOUBLE PRECISION RANDNUMBER,TIME,TIMELIMIT
        DOUBLE PRECISION RLIGHTX1TPDT(1000000),RLIGHTX2TPDT(1000000)
     $,RLIGHTX3TPDT(1000000)
        DOUBLE PRECISION RLIGHTX1T(1000000),RLIGHTX2T(1000000)
     $,RLIGHTX3T(1000000)
        DOUBLE PRECISION VLIGHTX1(1000000),VLIGHTX2(1000000),
     $VLIGHTX3(1000000)
        DOUBLE PRECISION VLIGHT0,NORMX1,NORMX2,NORMX3,DELTAT
        DOUBLE PRECISION POPOUT,A1,A2,A3,A4,A5,A6,A7,A8,A9
        DOUBLE PRECISION A10,A11,A12,A13,A14,A15,A16,A17,A18
        DOUBLE PRECISION RCOUNT,RLIGHTS,TFLAG(1000000)
       DOUBLE PRECISION WALLX1MINUSCUTOFF,WALLX1PLUSCUTOFF
       DOUBLE PRECISION WALLX2MINUSCUTOFF,WALLX2PLUSCUTOFF
       DOUBLE PRECISION WALLX3MINUSCUTOFF,WALLX3PLUSCUTOFF
       DOUBLE PRECISION GRADF(3),XDIST(3),TERM1,TERM2
       DOUBLE PRECISION GNORM,VNORM,VN,THETAI
       DOUBLE PRECISION NTIG,MAGRATG,NTI,MAGRAT
       DOUBLE PRECISION RPER,RPAR,TIMEMULTIPLIER
       DOUBLE PRECISION BIGRPAR,BIGRPER,BIGR
       DOUBLE PRECISION NX1,NX2,NX3,RADIUS
       DOUBLE PRECISION POWERX1(1000000),POWERX2(1000000),
     $POWERX3(1000000)
       DOUBLE PRECISION IRRAD(1000000),IRRADO(1000000),REF,RAYTOL
       DOUBLE PRECISION TOTALFACEPOWERX1MINUS,TOTALFACEPOWERX1PLUS
       DOUBLE PRECISION TOTALFACEPOWERX2MINUS,TOTALFACEPOWERX2PLUS
       DOUBLE PRECISION TOTALFACEPOWERX3MINUS,TOTALFACEPOWERX3PLUS
       DOUBLE PRECISION IRRADOX1MINUS,IRRADOX1PLUS
       DOUBLE PRECISION IRRADOX2MINUS,IRRADOX2PLUS
       DOUBLE PRECISION IRRADOX3MINUS,IRRADOX3PLUS
       INTEGER RAYCOUNT,RACKX1X2,RACKX2X3,RACKX1X3,RACKX1,RACKX2,RACKX3
       DOUBLE PRECISION FORPLUSX3SOURCETUBEX1,FORPLUSX3SOURCETUBEX2
       DOUBLE PRECISION FORMINUSX3SOURCETUBEX1,FORMINUSX3SOURCETUBEX2
       DOUBLE PRECISION FORPLUSX2SOURCETUBEX1,FORPLUSX2SOURCETUBEX3
       DOUBLE PRECISION FORMINUSX2SOURCETUBEX1,FORMINUSX2SOURCETUBEX3
       DOUBLE PRECISION FORPLUSX1SOURCETUBEX2,FORPLUSX1SOURCETUBEX3
       DOUBLE PRECISION FORMINUSX1SOURCETUBEX2,FORMINUSX1SOURCETUBEX3
       INTEGER X1MINUSON,X1PLUSON,X2MINUSON,X2PLUSON,X3MINUSON,X3PLUSON
       DOUBLE PRECISION RAYDENSITY
       INTEGER NRAYSPLUSX1,NRAYSMINUSX1
       INTEGER NRAYSPLUSX2,NRAYSMINUSX2
       INTEGER NRAYSPLUSX3,NRAYSMINUSX3
        OPEN(UNIT=38,FILE='PATH.dat',STATUS='UNKNOWN')
        OPEN(UNIT=39,FILE='LAPLACIAN-SMOOTHED-REAL3D.dat',
     $STATUS='UNKNOWN')


 299   FORMAT(F16.8,1X,F16.8,1X,F16.8,F16.8,1X,F16.8,1X,F16.4
     $,1X,F16.4,1X,F16.4,1X,F16.8,1X,F16.8,1X,F16.8,1X,F16.8,1X,
     $F16.8,1X,F16.8,1X,F16.8,1X,F16.8,1X,F16.8,1X,F16.8,1X,F16.8,
     $1X,F16.8,1X,F16.8,1X,F16.8)

CCCCCCCCCCCCCCCCCCCCCCCCC
C      KEY PARAMETERS
CCCCCCCCCCCCCCCCCCCCCCCCC

       MOVIE=1
       TIMEMULTIPLIER=5.0D0
       VLIGHT0=299792458.0D0
       REFLECTIONS=1
       RACKX1X3=1
       RACKX2X3=1
       RACKX1X2=1
       RACKX1=0
       RACKX2=0
       RACKX3=0

CCCCCCCCCCCCCCCCCCCCC
C    GA Params 1-18
CCCCCCCCCCCCCCCCCCCCC

       A1= 0.566790D0
       A2= 0.107683D0
       A3= 0.174475D0
       A4= 0.636496D0
       A5= 0.215733D0
       A6= 0.195423D0
       A7= 0.515307D0
       A8= 0.251739D0
       A9= 0.421156D0
       A10=0.740410D0
       A11=0.416287D0
       A12=0.578356D0
       A13=0.586021D0
       A14=0.393860D0
       A15=0.197936D0
       A16=0.597078D0
       A17=0.690145D0
       A18=0.199086D0

CCCCCCCCCCCCCCCCCCCCC
C    GA Params 19-30
CCCCCCCCCCCCCCCCCCCCC

       FORPLUSX3SOURCETUBEX1=1.908733D0
       FORPLUSX3SOURCETUBEX2=0.207362D0
       FORMINUSX3SOURCETUBEX1=1.691644D0
       FORMINUSX3SOURCETUBEX2=0.295097D0
       FORPLUSX2SOURCETUBEX1=0.326440D0
       FORPLUSX2SOURCETUBEX3=0.327684D0
       FORMINUSX2SOURCETUBEX1=0.913640D0
       FORMINUSX2SOURCETUBEX3=0.334437D0
       FORPLUSX1SOURCETUBEX2=0.119917D0
       FORPLUSX1SOURCETUBEX3=0.282774D0
       FORMINUSX1SOURCETUBEX2=0.214931D0
       FORMINUSX1SOURCETUBEX3=0.359765D0
       
CCCCCCCCCCCCCCCCCCCCC
C    GA Params 31-36
CCCCCCCCCCCCCCCCCCCCC

      TOTALFACEPOWERX1MINUS=5660545.216791D0
      TOTALFACEPOWERX1PLUS=5683012.004730D0
      TOTALFACEPOWERX2MINUS=7224669.407077D0
      TOTALFACEPOWERX2PLUS=6288994.960493D0
      TOTALFACEPOWERX3MINUS=3279214.234650D0
      TOTALFACEPOWERX3PLUS=4027783.567187D0

CCCCCCCCCCCCCCCCCCCCCCCCC
C      SOURCETUBE
CCCCCCCCCCCCCCCCCCCCCCCCC

C      RAYDENSITY=10000
      RAYDENSITY=2000

       NRAYSPLUSX1=RAYDENSITY*FORPLUSX1SOURCETUBEX2
     $*FORPLUSX1SOURCETUBEX3
       NRAYSMINUSX1=RAYDENSITY*FORMINUSX1SOURCETUBEX2
     $*FORMINUSX1SOURCETUBEX3
       NRAYSPLUSX2=RAYDENSITY*FORPLUSX2SOURCETUBEX1
     $*FORPLUSX2SOURCETUBEX3
       NRAYSMINUSX2=RAYDENSITY*FORMINUSX2SOURCETUBEX1
     $*FORMINUSX2SOURCETUBEX3
       NRAYSPLUSX3=RAYDENSITY*FORPLUSX3SOURCETUBEX1
     $*FORPLUSX3SOURCETUBEX2
       NRAYSMINUSX3=RAYDENSITY*FORMINUSX3SOURCETUBEX1
     $*FORMINUSX3SOURCETUBEX2

       WRITE(*,*)'TOTAL RAYS=',
     $NRAYSPLUSX1+NRAYSMINUSX1+NRAYSPLUSX2+
     $NRAYSMINUSX2+NRAYSPLUSX3+NRAYSMINUSX3

       X1MINUSON=1
       X1PLUSON=1
       X2MINUSON=1
       X2PLUSON=1
       X3MINUSON=1
       X3PLUSON=1

CCCCCCCCCCCCCCCCCCCCCCCCC
C      VOXEL MESH
CCCCCCCCCCCCCCCCCCCCCCCCC

       DELTAX1=0.05D0
       DELTAX2=0.05D0
       DELTAX3=0.05D0
       NVOXELX1=20
       NVOXELX2=20
       NVOXELX3=20

CCCCCCCCCCCCC
C     TARGETS
CCCCCCCCCCCCC

       NTARGETSX1=9
       NTARGETSX2=3
       NTARGETSX3=3
       TARDELTAX1=5.0D0*DELTAX1
       TARDELTAX2=5.0D0*DELTAX2
       TARDELTAX3=5.0D0*DELTAX3

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      TARGET #1
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

       COUNT=0

        IF(RACKX2X3 .EQ. 1)THEN
        I1=0
        X1=TARDELTAX1*I1
        DO I2=-NTARGETSX2,NTARGETSX2
         X2=TARDELTAX2*I2
          DO I3=-NTARGETSX3,NTARGETSX3
           X3=TARDELTAX3*I3
           IF(I2 .EQ. 0 .OR. I3 .EQ. 0)THEN
           GOTO 22
           ENDIF
           COUNT=COUNT+1
           TARGETX1(COUNT)=X1
           TARGETX2(COUNT)=X2
           TARGETX3(COUNT)=X3
           TARGETRADIUSX1(COUNT)=2.75D0*DELTAX1
           TARGETRADIUSX2(COUNT)=2.75D0*DELTAX2
           TARGETRADIUSX3(COUNT)=2.75D0*DELTAX3
           PX1(COUNT)=6.0D0
           PX2(COUNT)=6.0D0
           PX3(COUNT)=6.0D0
           TARGETABSORB(COUNT)=0.0D0
22       ENDDO
        ENDDO
        ENDIF

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      TARGET #2
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

       IF(RACKX1X3 .EQ. 1)THEN
       DO I1=-NTARGETSX1,NTARGETSX1
        X1=TARDELTAX1*I1
         I2=0
         X2=TARDELTAX2*I2
          DO I3=-NTARGETSX3,NTARGETSX3
           X3=TARDELTAX3*I3
           IF(I1 .EQ. 0 .OR. I3 .EQ. 0)THEN
           GOTO 23
           ENDIF
           COUNT=COUNT+1
           TARGETX1(COUNT)=X1
           TARGETX2(COUNT)=X2
           TARGETX3(COUNT)=X3
           TARGETRADIUSX1(COUNT)=2.75D0*DELTAX1
           TARGETRADIUSX2(COUNT)=2.75D0*DELTAX2
           TARGETRADIUSX3(COUNT)=2.75D0*DELTAX3
           PX1(COUNT)=2.0D0
           PX2(COUNT)=2.0D0
           PX3(COUNT)=2.0D0
           TARGETABSORB(COUNT)=0.0D0
23         ENDDO
        ENDDO
        ENDIF

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      TARGET #3
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

       IF(RACKX1X2 .EQ. 1)THEN
       DO I1=-NTARGETSX1,NTARGETSX1
        X1=TARDELTAX1*I1
        DO I2=-NTARGETSX2,NTARGETSX2
         X2=TARDELTAX2*I2
           IF(I1 .EQ. 0 .OR. I2 .EQ. 0)THEN
           GOTO 24
           ENDIF
           I3=0
           X3=TARDELTAX3*I3
           COUNT=COUNT+1
           TARGETX1(COUNT)=X1
           TARGETX2(COUNT)=X2
           TARGETX3(COUNT)=X3
           TARGETRADIUSX1(COUNT)=2.75D0*DELTAX1
           TARGETRADIUSX2(COUNT)=2.75D0*DELTAX2
           TARGETRADIUSX3(COUNT)=2.75D0*DELTAX3
           PX1(COUNT)=2.0D0
           PX2(COUNT)=2.0D0
           PX3(COUNT)=2.0D0
           TARGETABSORB(COUNT)=0.0D0
24      ENDDO
        ENDDO
        ENDIF

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      TARGET #4
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

       IF(RACKX1 .EQ. 1)THEN
       DO I1=-NTARGETSX1,NTARGETSX1
        X1=TARDELTAX1*I1
         I2=0
         X2=TARDELTAX2*I2
           I3=0
           X3=TARDELTAX3*I3
           COUNT=COUNT+1
           TARGETX1(COUNT)=X1
           TARGETX2(COUNT)=X2
           TARGETX3(COUNT)=X3
           TARGETRADIUSX1(COUNT)=2.75D0*DELTAX1
           TARGETRADIUSX2(COUNT)=2.75D0*DELTAX2
           TARGETRADIUSX3(COUNT)=2.75D0*DELTAX3
           PX1(COUNT)=2.0D0
           PX2(COUNT)=2.0D0
           PX3(COUNT)=2.0D0
           TARGETABSORB(COUNT)=0.0D0
         ENDDO
        ENDIF

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      TARGET #5
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

        IF(RACKX2 .EQ. 1)THEN
        I1=0
        X1=TARDELTAX1*I1
        DO I2=-NTARGETSX2,NTARGETSX2
         X2=TARDELTAX2*I2
           I3=0
           X3=TARDELTAX3*I3
           COUNT=COUNT+1
           TARGETX1(COUNT)=X1
           TARGETX2(COUNT)=X2
           TARGETX3(COUNT)=X3
           TARGETRADIUSX1(COUNT)=2.75D0*DELTAX1
           TARGETRADIUSX2(COUNT)=2.75D0*DELTAX2
           TARGETRADIUSX3(COUNT)=2.75D0*DELTAX3
           PX1(COUNT)=2.0D0
           PX2(COUNT)=2.0D0
           PX3(COUNT)=2.0D0
           TARGETABSORB(COUNT)=0.0D0
         ENDDO
        ENDIF

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      TARGET #6
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC


       IF(RACKX3 .EQ. 1)THEN
        I1=0
        X1=TARDELTAX1*I1
         I2=0
         X2=TARDELTAX2*I2
          DO I3=-NTARGETSX3,NTARGETSX3
           X3=TARDELTAX3*I3
           COUNT=COUNT+1
           TARGETX1(COUNT)=X1
           TARGETX2(COUNT)=X2
           TARGETX3(COUNT)=X3
           TARGETRADIUSX1(COUNT)=2.75D0*DELTAX1
           TARGETRADIUSX2(COUNT)=2.75D0*DELTAX2
           TARGETRADIUSX3(COUNT)=2.75D0*DELTAX3
           PX1(COUNT)=2.0D0
           PX2(COUNT)=2.0D0
           PX3(COUNT)=2.0D0
           TARGETABSORB(COUNT)=0.0D0
         ENDDO
        ENDIF
        NTARGETS=COUNT

CCCCCCCCCCCCCCCCCCCCCCCCC
C     REFLECTION DATA
CCCCCCCCCCCCCCCCCCCCCCCCC

      WALLX1MINUSCUTOFF=-3*(NVOXELX1+1)*DELTAX1
      WALLX1PLUSCUTOFF=3*(NVOXELX1+1)*DELTAX1
      WALLX2MINUSCUTOFF=-(NVOXELX2+1)*DELTAX2
      WALLX2PLUSCUTOFF=(NVOXELX2+1)*DELTAX2
      WALLX3MINUSCUTOFF=-(NVOXELX3+1)*DELTAX3
      WALLX3PLUSCUTOFF=(NVOXELX3+1)*DELTAX3
c      WRITE(*,*)WALLX1CUTOFF1
c      READ(*,*)
      NTIG=10.0D0
      MAGRATG=1.0D0
      NTI=2.0D0
      MAGRAT=1.0D0
      
      IRRADOX1MINUS=TOTALFACEPOWERX1MINUS/NRAYSMINUSX1
      IRRADOX1PLUS=TOTALFACEPOWERX1PLUS/NRAYSPLUSX1
      IRRADOX2MINUS=TOTALFACEPOWERX2MINUS/NRAYSMINUSX2
      IRRADOX2PLUS=TOTALFACEPOWERX2PLUS/NRAYSPLUSX2
      IRRADOX3MINUS=TOTALFACEPOWERX3MINUS/NRAYSMINUSX3
      IRRADOX3PLUS=TOTALFACEPOWERX3PLUS/NRAYSPLUSX3
      RAYTOL=0.000001D0
      REF=0.0D0
      RADIUS=0.0001D0

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      RANDOM NUMBER GENERATOR
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

        RANDSEED=201
        IRNUM=2011
        RANDNUMBER=111.1D0
        DO IR=1,RANDSEED
         CALL GETRAND(IRNUM,RANDNUMBER)
        ENDDO

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      INITIALIZATION
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

       DO IR=1,1000000
        TFLAG(IR)=0
       ENDDO
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      PROPAGATED RLIGHTS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

       DELTAT=((DELTAX1+DELTAX2+DELTAX3)/3.0D0)/VLIGHT0
       TIMELIMIT=TIMEMULTIPLIER*
     $((2.0D0*NVOXELX1*DELTAX1+2.0D0*NVOXELX2*DELTAX2
     $+2.0D0*NVOXELX3*DELTAX3)/3.0D0)/VLIGHT0

       RAYCOUNT=0
   


CCCCCCCCCCCCCCCCCCCC
C       -X1 DIRECTION
CCCCCCCCCCCCCCCCCCCC

        IF(X1MINUSON .EQ. 1)THEN
c       DO I=-LIGHTROWSFORX1,LIGHTROWSFORX1
        DO IR=1,NRAYSMINUSX1
         RAYCOUNT=RAYCOUNT+1
         IRRAD(RAYCOUNT)=IRRADOX1MINUS
         IRRADO(RAYCOUNT)=IRRADOX1MINUS
         RLIGHTX1T(RAYCOUNT)=WALLX1PLUSCUTOFF
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=FORMINUSX1SOURCETUBEX2*(RANDNUMBER-0.5D0)/0.5D0
         RLIGHTX2T(RAYCOUNT)=POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=FORMINUSX1SOURCETUBEX3*(RANDNUMBER-0.5D0)/0.5D0
         RLIGHTX3T(RAYCOUNT)=POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX1=A1*POPOUT-1.0D0
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX2=A2*POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX3=A3*POPOUT
         NORMX1=NORMX1/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         NORMX2=NORMX2/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         NORMX3=NORMX3/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         VLIGHTX1(RAYCOUNT)=NORMX1*VLIGHT0
         VLIGHTX2(RAYCOUNT)=NORMX2*VLIGHT0
         VLIGHTX3(RAYCOUNT)=NORMX3*VLIGHT0
         POWERX1(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX1
         POWERX2(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX2
         POWERX3(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX3
        ENDDO
c       ENDDO
        ENDIF

CCCCCCCCCCCCCCCCCCCC
C       +X1 DIRECTION
CCCCCCCCCCCCCCCCCCCC

        IF(X1PLUSON .EQ. 1)THEN
c       DO I=-LIGHTROWSFORX1,LIGHTROWSFORX1
        DO IR=NRAYSMINUSX1+1,NRAYSMINUSX1+NRAYSPLUSX1
         RAYCOUNT=RAYCOUNT+1
         IRRAD(RAYCOUNT)=IRRADOX1PLUS
         IRRADO(RAYCOUNT)=IRRADOX1PLUS
         RLIGHTX1T(RAYCOUNT)=WALLX1MINUSCUTOFF
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=FORPLUSX1SOURCETUBEX2*(RANDNUMBER-0.5D0)/0.5D0
         RLIGHTX2T(RAYCOUNT)=POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=FORPLUSX1SOURCETUBEX3*(RANDNUMBER-0.5D0)/0.5D0
         RLIGHTX3T(RAYCOUNT)=POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX1=A4*POPOUT+1.0D0
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX2=A5*POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX3=A6*POPOUT
         NORMX1=NORMX1/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         NORMX2=NORMX2/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         NORMX3=NORMX3/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         VLIGHTX1(RAYCOUNT)=NORMX1*VLIGHT0
         VLIGHTX2(RAYCOUNT)=NORMX2*VLIGHT0
         VLIGHTX3(RAYCOUNT)=NORMX3*VLIGHT0
         POWERX1(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX1
         POWERX2(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX2
         POWERX3(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX3
        ENDDO
c       ENDDO
        ENDIF
CCCCCCCCCCCCCCCCCCCC
C       -X2 DIRECTION
CCCCCCCCCCCCCCCCCCCC

        IF(X2MINUSON .EQ. 1)THEN
c       DO I=-LIGHTROWSFORX2,LIGHTROWSFORX2
        DO IR=NRAYSMINUSX1+NRAYSPLUSX1+1,NRAYSMINUSX1+NRAYSPLUSX1
     $+NRAYSMINUSX2
         RAYCOUNT=RAYCOUNT+1
         IRRAD(RAYCOUNT)=IRRADOX2MINUS
         IRRADO(RAYCOUNT)=IRRADOX2MINUS
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=FORMINUSX2SOURCETUBEX1*(RANDNUMBER-0.5D0)/0.5D0
         RLIGHTX1T(RAYCOUNT)=POPOUT
         RLIGHTX2T(RAYCOUNT)=WALLX2PLUSCUTOFF
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=FORMINUSX2SOURCETUBEX3*(RANDNUMBER-0.5D0)/0.5D0
         RLIGHTX3T(RAYCOUNT)=POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX1=A7*POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX2=A8*POPOUT-1.0D0
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX3=A9*POPOUT
         NORMX1=NORMX1/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         NORMX2=NORMX2/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         NORMX3=NORMX3/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         VLIGHTX1(RAYCOUNT)=NORMX1*VLIGHT0
         VLIGHTX2(RAYCOUNT)=NORMX2*VLIGHT0
         VLIGHTX3(RAYCOUNT)=NORMX3*VLIGHT0
         POWERX1(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX1
         POWERX2(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX2
         POWERX3(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX3
        ENDDO
c       ENDDO
        ENDIF

CCCCCCCCCCCCCCCCCCCC
C       +X2 DIRECTION
CCCCCCCCCCCCCCCCCCCC

        IF(X2PLUSON .EQ. 1)THEN
c       DO I=-LIGHTROWSFORX2,LIGHTROWSFORX2
        DO IR=NRAYSMINUSX1+NRAYSPLUSX1+NRAYSMINUSX2+1,
     $NRAYSMINUSX1+NRAYSPLUSX1+NRAYSMINUSX2+NRAYSPLUSX2
         RAYCOUNT=RAYCOUNT+1
         IRRAD(RAYCOUNT)=IRRADOX2PLUS
         IRRADO(RAYCOUNT)=IRRADOX2PLUS
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=FORPLUSX2SOURCETUBEX1*(RANDNUMBER-0.5D0)/0.5D0
         RLIGHTX1T(RAYCOUNT)=POPOUT
         RLIGHTX2T(RAYCOUNT)=WALLX2MINUSCUTOFF
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=FORPLUSX2SOURCETUBEX3*(RANDNUMBER-0.5D0)/0.5D0
         RLIGHTX3T(RAYCOUNT)=POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX1=A10*POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX2=A11*POPOUT+1.0D0
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX3=A12*POPOUT
         NORMX1=NORMX1/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         NORMX2=NORMX2/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         NORMX3=NORMX3/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         VLIGHTX1(RAYCOUNT)=NORMX1*VLIGHT0
         VLIGHTX2(RAYCOUNT)=NORMX2*VLIGHT0
         VLIGHTX3(RAYCOUNT)=NORMX3*VLIGHT0
         POWERX1(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX1
         POWERX2(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX2
         POWERX3(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX3
        ENDDO
c       ENDDO
        ENDIF



   
CCCCCCCCCCCCCCCCCCCC
C       -X3 DIRECTION
CCCCCCCCCCCCCCCCCCCC


c       DO I=-LIGHTROWSFORX3,LIGHTROWSFORX3
        IF(X3MINUSON .EQ. 1)THEN
        DO IR=NRAYSMINUSX1+NRAYSPLUSX1+NRAYSMINUSX2+NRAYSPLUSX2+1,
     $NRAYSMINUSX1+NRAYSPLUSX1+NRAYSMINUSX2+NRAYSPLUSX2+NRAYSMINUSX3
         RAYCOUNT=RAYCOUNT+1
         IRRAD(RAYCOUNT)=IRRADOX3MINUS
         IRRADO(RAYCOUNT)=IRRADOX3MINUS
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=FORMINUSX3SOURCETUBEX1*(RANDNUMBER-0.5D0)/0.5D0
         RLIGHTX1T(RAYCOUNT)=POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=FORMINUSX3SOURCETUBEX2*(RANDNUMBER-0.5D0)/0.5D0
         RLIGHTX2T(RAYCOUNT)=POPOUT
         RLIGHTX3T(RAYCOUNT)=WALLX3PLUSCUTOFF
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX1=A13*POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX2=A14*POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX3=A15*POPOUT-1.0D0
         NORMX1=NORMX1/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         NORMX2=NORMX2/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         NORMX3=NORMX3/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         VLIGHTX1(RAYCOUNT)=NORMX1*VLIGHT0
         VLIGHTX2(RAYCOUNT)=NORMX2*VLIGHT0
         VLIGHTX3(RAYCOUNT)=NORMX3*VLIGHT0
         POWERX1(RAYCOUNT)=IRRAD(IR)*NORMX1
         POWERX2(RAYCOUNT)=IRRAD(IR)*NORMX2
         POWERX3(RAYCOUNT)=IRRAD(IR)*NORMX3
        ENDDO
c       ENDDO
       ENDIF

CCCCCCCCCCCCCCCCCCCC
C       +X3 DIRECTION
CCCCCCCCCCCCCCCCCCCC

        IF(X3PLUSON .EQ. 1)THEN
c       DO I=-LIGHTROWSFORX3,LIGHTROWSFORX3
        DO IR=NRAYSMINUSX1+NRAYSPLUSX1+NRAYSMINUSX2+NRAYSPLUSX2
     $+NRAYSMINUSX3+1,NRAYSMINUSX1+NRAYSPLUSX1+NRAYSMINUSX2+NRAYSPLUSX2
     $+NRAYSMINUSX3+NRAYSPLUSX3
         RAYCOUNT=RAYCOUNT+1
         IRRAD(RAYCOUNT)=IRRADOX3PLUS
         IRRADO(RAYCOUNT)=IRRADOX3PLUS
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=FORPLUSX3SOURCETUBEX1*(RANDNUMBER-0.5D0)/0.5D0
         RLIGHTX1T(RAYCOUNT)=POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=FORPLUSX3SOURCETUBEX2*(RANDNUMBER-0.5D0)/0.5D0
         RLIGHTX2T(RAYCOUNT)=POPOUT
         RLIGHTX3T(RAYCOUNT)=WALLX3MINUSCUTOFF
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX1=A16*POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX2=A17*POPOUT
         CALL GETRAND(IRNUM,RANDNUMBER)
         POPOUT=(RANDNUMBER-0.5D0)/0.5D0
         NORMX3=A18*POPOUT+1.0D0
         NORMX1=NORMX1/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         NORMX2=NORMX2/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         NORMX3=NORMX3/
     $(DSQRT(NORMX1**2.0D0+NORMX2**2.0D0+NORMX3**2.0D0))
         VLIGHTX1(RAYCOUNT)=NORMX1*VLIGHT0
         VLIGHTX2(RAYCOUNT)=NORMX2*VLIGHT0
         VLIGHTX3(RAYCOUNT)=NORMX3*VLIGHT0
         POWERX1(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX1
         POWERX2(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX2
         POWERX3(RAYCOUNT)=IRRAD(RAYCOUNT)*NORMX3
        ENDDO
c       ENDDO
        ENDIF

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      PROPAGATE THE RLIGHTS
C
C      THIS COMPUTES THE RLIGHTS INTERSECTION
C      WITH THE VOXELS, THUS COMPUTING  THE POWER CONTENT
C      IN A VOXEL. THE RESIDENCE IS TAGGED AND ASSUMES IT IS
C      A CONTINUOUS BEAM. IF THE BEAM IS REFLECTED LATER AND
C      RETURNS THROUGH THE VOXEL THEN ANOTHER SOURCE IS ADDED
C      TO THE PREVIOUS VALUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

       TIME=0.0D0
       DO WHILE(TIME .LE. TIMELIMIT)
        WRITE(*,*)'TIME=',TIME/TIMELIMIT

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C    WITH NO RAY REFLECTIONS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      IF(REFLECTIONS .EQ. 0)THEN
         DO IR=1,RAYCOUNT
          DO I=1,NTARGETS
           CONDITION(I)=(
     $(DABS((RLIGHTX1T(IR)-TARGETX1(I)))/TARGETRADIUSX1(I))**PX1(I)+
     $(DABS((RLIGHTX2T(IR)-TARGETX2(I)))/TARGETRADIUSX2(I))**PX2(I)+
     $(DABS((RLIGHTX3T(IR)-TARGETX3(I)))/TARGETRADIUSX3(I))**PX3(I))
         IF(CONDITION(I) .LE. 1.0D0)THEN
          TFLAG(IR)=1.0D0
          GOTO 144
         ENDIF
         ENDDO
144      RLIGHTX1TPDT(IR)=RLIGHTX1T(IR)+VLIGHTX1(IR)*DELTAT
         RLIGHTX2TPDT(IR)=RLIGHTX2T(IR)+VLIGHTX2(IR)*DELTAT
         RLIGHTX3TPDT(IR)=RLIGHTX3T(IR)+VLIGHTX3(IR)*DELTAT
        ENDDO
       ENDIF

        IF(REFLECTIONS .EQ. 1)THEN

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C    WITH RAY REFLECTIONS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

       DO IR=1,RAYCOUNT

CCCCCCCCCCCCCC
C     CHECKING TARGETS
CCCCCCCCCCCCCC

          IKEY=1
          DO I=1,NTARGETS
           CONDITION(I)=(
     $(DABS((RLIGHTX1T(IR)-TARGETX1(I)))/TARGETRADIUSX1(I))**PX1(I)+
     $(DABS((RLIGHTX2T(IR)-TARGETX2(I)))/TARGETRADIUSX2(I))**PX2(I)+
     $(DABS((RLIGHTX3T(IR)-TARGETX3(I)))/TARGETRADIUSX3(I))**PX3(I))
         IF(CONDITION(I) .LE. 1.0D0)THEN
          TFLAG(IR)=1.0D0
          IKEY=I
          GOTO 145
         ENDIF
        ENDDO

145   IF(
     $(CONDITION(IKEY) .LE. 1.0D0)
     $.OR. (RLIGHTX1T(IR) .GE. WALLX1PLUSCUTOFF)
     $.OR. (RLIGHTX1T(IR) .LE. WALLX1MINUSCUTOFF)
     $.OR. (RLIGHTX2T(IR) .GE. WALLX2PLUSCUTOFF)
     $.OR. (RLIGHTX2T(IR) .LE. WALLX2MINUSCUTOFF)
     $.OR. (RLIGHTX3T(IR) .GE. WALLX3PLUSCUTOFF)
     $.OR. (RLIGHTX3T(IR) .LE. WALLX3MINUSCUTOFF)
     $)THEN

c        WRITE(*,*)'IN'
c        READ(*,*)

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      WALLS (6 OF THEM)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

          IF(RLIGHTX1T(IR) .GE. WALLX1PLUSCUTOFF)THEN
           NX1=-1.0D0
           NX2=0.0D0
           NX3=0.0D0
           GOTO 123
          ENDIF
          IF(RLIGHTX1T(IR) .LE. WALLX1MINUSCUTOFF)THEN
           NX1=1.0D0
           NX2=0.0D0
           NX3=0.0D0
           GOTO 123
          ENDIF
          IF(RLIGHTX2T(IR) .GE. WALLX2PLUSCUTOFF)THEN
           NX1=0.0D0
           NX2=-1.0D0
           NX3=0.0D0
           GOTO 123
          ENDIF
          IF(RLIGHTX2T(IR) .LE. WALLX2MINUSCUTOFF)THEN
           NX1=0.0D0
           NX2=1.0D0
           NX3=0.0D0
           GOTO 123
          ENDIF
          IF(RLIGHTX3T(IR) .GE. WALLX3PLUSCUTOFF)THEN
           NX1=0.0D0
           NX2=0.0D0
           NX3=-1.0D0
           GOTO 123
          ENDIF
          IF(RLIGHTX3T(IR) .LE. WALLX3MINUSCUTOFF)THEN
           NX1=0.0D0
           NX2=0.0D0
           NX3=1.0D0
           GOTO 123
          ENDIF

CCCCCCCCCCCCCCCCCCCCCCCC
C        IF THE TARGET
CCCCCCCCCCCCCCCCCCCCCCCC

         TFLAG(IR)=1.0D0

         GRADF(1)=0.0D0
         GRADF(2)=0.0D0
         GRADF(3)=0.0D0

         XDIST(1)=RLIGHTX1T(IR)-TARGETX1(IKEY)
         XDIST(2)=RLIGHTX2T(IR)-TARGETX2(IKEY)
         XDIST(3)=RLIGHTX3T(IR)-TARGETX3(IKEY)
     
CCCCCCCCCCC
C   COMPUTING THE NORMALS
CCCCCCCCCCC

       IF(DABS(XDIST(1)) .GT. 0.00000001D0)THEN
        TERM1=PX1(IKEY)*(((DABS(XDIST(1)))/TARGETRADIUSX1(IKEY))
     $**(PX1(IKEY)-1.0D0))
        TERM2=XDIST(1)/(TARGETRADIUSX1(IKEY)*DABS(XDIST(1)))
        GRADF(1)=TERM1*TERM2
       ENDIF
 
       IF(DABS(XDIST(2)) .GT. 0.00000001D0)THEN
        TERM1=PX2(IKEY)*(((DABS(XDIST(2)))/TARGETRADIUSX2(IKEY))
     $**(PX2(IKEY)-1.0D0))
        TERM2=XDIST(2)/(TARGETRADIUSX2(IKEY)*DABS(XDIST(2)))
        GRADF(2)=TERM1*TERM2
       ENDIF

       IF(DABS(XDIST(3)) .GT. 0.00000001D0)THEN
        TERM1=PX3(IKEY)*(((DABS(XDIST(3)))/TARGETRADIUSX3(IKEY))
     $**(PX3(IKEY)-1.0D0))
        TERM2=XDIST(3)/(TARGETRADIUSX3(IKEY)*DABS(XDIST(3)))
        GRADF(3)=TERM1*TERM2
       ENDIF

        GNORM=DSQRT(GRADF(1)**2.0D0+GRADF(2)**2.0D0+GRADF(3)**2.0D0)
                    
        GRADF(1)=GRADF(1)/GNORM
        GRADF(2)=GRADF(2)/GNORM
        GRADF(3)=GRADF(3)/GNORM

        NX1=GRADF(1)
        NX2=GRADF(2)
        NX3=GRADF(3)

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C        DETERMINING THE NORMAL PROJECTION AND SUBTRACTING IT OUT
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

123     VNORM=DSQRT
     $(VLIGHTX1(IR)**2.0D0+VLIGHTX2(IR)**2.0D0+VLIGHTX3(IR)**2.0D0)
        VN=VLIGHTX1(IR)*NX1+VLIGHTX2(IR)*NX2+VLIGHTX3(IR)*NX3

        IF(VN .GT. 0.0D0)THEN
         GOTO 777
        ENDIF

          THETAI=ACOS(DABS(VN)/VNORM)

          VLIGHTX1(IR)=VLIGHTX1(IR)-2.0D0*VN*NX1
          VLIGHTX2(IR)=VLIGHTX2(IR)-2.0D0*VN*NX2
          VLIGHTX3(IR)=VLIGHTX3(IR)-2.0D0*VN*NX3

CCCCCCCCCCCCCCCCCCCCCCCCCCC
C       IF X1+ WALL
CCCCCCCCCCCCCCCCCCCCCCCCCCC

         IF(RLIGHTX1T(IR) .GE. WALLX1PLUSCUTOFF)THEN
          IF(DABS((SIN(THETAI))/NTIG) .GT. 1.0D0)THEN
           RPER=1.0D0
           RPAR=1.0D0
          ENDIF
          IF(DABS((SIN(THETAI))/NTIG) .LE. 1.0D0)THEN
           RPER=
     $(COS(THETAI)-(1.0D0/MAGRATG)
     $*(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)/
     $(COS(THETAI)+(1.0D0/MAGRATG)
     $*(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)

           RPAR=(
     $(1.0D0/MAGRATG)*(NTIG**2.0D0)*COS(THETAI)
     $-(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
     $/(
     $(1.0D0/MAGRATG)*(NTIG**2.0D0)*COS(THETAI)
     $+(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
          ENDIF
          RLIGHTX1T(IR)=WALLX1PLUSCUTOFF-1.5D0*DELTAX1
          GOTO 124
         ENDIF

CCCCCCCCCCCCCCCCCCCCCCCCCCC
C       IF X1- WALL
CCCCCCCCCCCCCCCCCCCCCCCCCCC

         IF(RLIGHTX1T(IR) .LE. WALLX1MINUSCUTOFF)THEN
          IF(DABS((SIN(THETAI))/NTIG) .GT. 1.0D0)THEN
           RPER=1.0D0
           RPAR=1.0D0
          ENDIF
          IF(DABS((SIN(THETAI))/NTIG) .LE. 1.0D0)THEN
           RPER=
     $(COS(THETAI)-(1.0D0/MAGRATG)
     $*(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)/
     $(COS(THETAI)+(1.0D0/MAGRATG)
     $*(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)

           RPAR=(
     $(1.0D0/MAGRATG)*(NTIG**2.0D0)*COS(THETAI)
     $-(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
     $/(
     $(1.0D0/MAGRATG)*(NTIG**2.0D0)*COS(THETAI)
     $+(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
          ENDIF
          RLIGHTX1T(IR)=WALLX1MINUSCUTOFF+1.5D0*DELTAX1
          GOTO 124
         ENDIF

CCCCCCCCCCCCCCCCCCCCCCCCCCC
C       IF X2+ WALL
CCCCCCCCCCCCCCCCCCCCCCCCCCC

         IF(RLIGHTX2T(IR) .GE. WALLX2PLUSCUTOFF)THEN
          IF(DABS((SIN(THETAI))/NTIG) .GT. 1.0D0)THEN
           RPER=1.0D0
           RPAR=1.0D0
          ENDIF
          IF(DABS((SIN(THETAI))/NTIG) .LE. 1.0D0)THEN
           RPER=
     $(COS(THETAI)-(1.0D0/MAGRATG)
     $*(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)/
     $(COS(THETAI)+(1.0D0/MAGRATG)
     $*(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)

           RPAR=(
     $(1.0D0/MAGRATG)*(NTIG**2.0D0)*COS(THETAI)
     $-(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
     $/(
     $(1.0D0/MAGRATG)*(NTIG**2.0D0)*COS(THETAI)
     $+(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
          ENDIF
          RLIGHTX2T(IR)=WALLX2PLUSCUTOFF-1.5D0*DELTAX2
          GOTO 124
         ENDIF

CCCCCCCCCCCCCCCCCCCCCCCCCCC
C       IF X2- WALL
CCCCCCCCCCCCCCCCCCCCCCCCCCC

         IF(RLIGHTX2T(IR) .LE. WALLX2MINUSCUTOFF)THEN
          IF(DABS((SIN(THETAI))/NTIG) .GT. 1.0D0)THEN
           RPER=1.0D0
           RPAR=1.0D0
          ENDIF
          IF(DABS((SIN(THETAI))/NTIG) .LE. 1.0D0)THEN
           RPER=
     $(COS(THETAI)-(1.0D0/MAGRATG)
     $*(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)/
     $(COS(THETAI)+(1.0D0/MAGRATG)
     $*(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)

           RPAR=(
     $(1.0D0/MAGRATG)*(NTIG**2.0D0)*COS(THETAI)
     $-(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
     $/(
     $(1.0D0/MAGRATG)*(NTIG**2.0D0)*COS(THETAI)
     $+(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
          ENDIF
          RLIGHTX2T(IR)=WALLX2MINUSCUTOFF+1.5D0*DELTAX2
          GOTO 124
         ENDIF

CCCCCCCCCCCCCCCCCCCCCCCCCCC
C       IF X3+ WALL
CCCCCCCCCCCCCCCCCCCCCCCCCCC

         IF(RLIGHTX3T(IR) .GE. WALLX3PLUSCUTOFF)THEN
          IF(DABS((SIN(THETAI))/NTIG) .GT. 1.0D0)THEN
           RPER=1.0D0
           RPAR=1.0D0
          ENDIF
          IF(DABS((SIN(THETAI))/NTIG) .LE. 1.0D0)THEN
           RPER=
     $(COS(THETAI)-(1.0D0/MAGRATG)
     $*(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)/
     $(COS(THETAI)+(1.0D0/MAGRATG)
     $*(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)

           RPAR=(
     $(1.0D0/MAGRATG)*(NTIG**2.0D0)*COS(THETAI)
     $-(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
     $/(
     $(1.0D0/MAGRATG)*(NTIG**2.0D0)*COS(THETAI)
     $+(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
          ENDIF
          RLIGHTX3T(IR)=WALLX3PLUSCUTOFF-1.5D0*DELTAX3
          GOTO 124
         ENDIF

CCCCCCCCCCCCCCCCCCCCCCCCCCC
C       IF X3- WALL
CCCCCCCCCCCCCCCCCCCCCCCCCCC

         IF(RLIGHTX3T(IR) .LE. WALLX3MINUSCUTOFF)THEN
          IF(DABS((SIN(THETAI))/NTIG) .GT. 1.0D0)THEN
           RPER=1.0D0
           RPAR=1.0D0
          ENDIF
          IF(DABS((SIN(THETAI))/NTIG) .LE. 1.0D0)THEN
           RPER=
     $(COS(THETAI)-(1.0D0/MAGRATG)
     $*(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)/
     $(COS(THETAI)+(1.0D0/MAGRATG)
     $*(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)

           RPAR=(
     $(1.0D0/MAGRATG)*(NTIG**2.0D0)*COS(THETAI)
     $-(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
     $/(
     $(1.0D0/MAGRATG)*(NTIG**2.0D0)*COS(THETAI)
     $+(NTIG**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
          ENDIF
          RLIGHTX3T(IR)=WALLX3MINUSCUTOFF+1.5D0*DELTAX3
          GOTO 124
         ENDIF

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      IF NOT A WALL=TARGET
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

          IF(DABS((SIN(THETAI))/NTI) .GT. 1.0D0)THEN
           RPER=1.0D0
           RPAR=1.0D0
          ENDIF
          IF(DABS((SIN(THETAI))/NTI) .LE. 1.0D0)THEN
           RPER=
     $(COS(THETAI)-(1.0D0/MAGRAT)
     $*(NTI**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)/
     $(COS(THETAI)+(1.0D0/MAGRAT)
     $*(NTI**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)

           RPAR=(
     $(1.0D0/MAGRAT)*(NTI**2.0D0)*COS(THETAI)
     $-(NTI**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
     $/(
     $(1.0D0/MAGRAT)*(NTI**2.0D0)*COS(THETAI)
     $+(NTI**2.0D0-(SIN(THETAI))**2.0D0)**0.5D0)
           ENDIF


CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C         REFLECTIVITIES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

124       BIGRPAR=RPAR**2.0D0
          BIGRPER=RPER**2.0D0
          BIGR=0.5D0*(BIGRPAR+BIGRPER)

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C         ABSORPTION AND IRRADIANCE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
            
      IF(CONDITION(IKEY) .LE. 1.0D0)THEN
       TARGETABSORB(IKEY)=TARGETABSORB(IKEY)
     $+(IRRAD(IR)-BIGR*IRRAD(IR))
      ENDIF
      IRRAD(IR)=BIGR*IRRAD(IR)

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C         AN ERROR CHECK-VELOCITY MAGNITUDE SHOULD NOT CHANGE)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

          VNORM=DSQRT
     $(VLIGHTX1(IR)**2.0D0+VLIGHTX2(IR)**2.0D0+VLIGHTX3(IR)**2.0D0)

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C         POWER IN EACH RAY
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

          POWERX1(IR)=VLIGHTX1(IR)*IRRAD(IR)/VNORM
          POWERX2(IR)=VLIGHTX2(IR)*IRRAD(IR)/VNORM
          POWERX3(IR)=VLIGHTX3(IR)*IRRAD(IR)/VNORM

          REF=REF+1.0D0

          ENDIF

CCCCCCCCCCCCCCCCCCCCC
C        TRAPPING THE LIGHT IF ABSORBED
CCCCCCCCCCCCCCCCCCCCC

 777     IF(IRRAD(IR)/IRRADO(IR) .LE. RAYTOL)THEN
          RLIGHTX1TPDT(IR)=RLIGHTX1T(IR)
          RLIGHTX2TPDT(IR)=RLIGHTX2T(IR)
          RLIGHTX3TPDT(IR)=RLIGHTX3T(IR)
          GOTO 779
         ENDIF

          RLIGHTX1TPDT(IR)=VLIGHTX1(IR)*DELTAT+RLIGHTX1T(IR)
          RLIGHTX2TPDT(IR)=VLIGHTX2(IR)*DELTAT+RLIGHTX2T(IR)
          RLIGHTX3TPDT(IR)=VLIGHTX3(IR)*DELTAT+RLIGHTX3T(IR)
C*********************
C        END LOOP OVER RAYS
C********************

779       ENDDO
         ENDIF

CCCCCCCCCCCCCC
C     MOVIES
CCCCCCCCCCCCCC

       IF(MOVIE .EQ. 1)THEN
       WRITE(38,*)'ZONE'

       DO IR=1,RAYCOUNT
        WRITE(38,299)RLIGHTX1TPDT(IR),RLIGHTX2TPDT(IR),RLIGHTX3TPDT(IR),
     $2.0D0*RADIUS,IRRAD(IR)/IRRADO(IR),VLIGHTX1(IR),VLIGHTX2(IR)
     $,VLIGHTX3(IR),POWERX1(IR)/IRRADO(IR),POWERX2(IR)/IRRADO(IR),
     $POWERX3(IR)/IRRADO(IR),0.0D0,0.0D0
       ENDDO

       COUNT=0
       DO I1=1,NTARGETS
           COUNT=COUNT+1
        WRITE(38,299)TARGETX1(COUNT),TARGETX2(COUNT),
     $TARGETX3(COUNT),2.0D0*TARGETRADIUSX1(COUNT),
     $0.0D0,0.0D0,0.0D0,0.0D0,0.0D0,0.0D0,0.0D0,
     $TARGETABSORB(COUNT)/(
     $TOTALFACEPOWERX1MINUS+
     $TOTALFACEPOWERX1PLUS+
     $TOTALFACEPOWERX2MINUS+
     $TOTALFACEPOWERX2PLUS+
     $TOTALFACEPOWERX3MINUS+
     $TOTALFACEPOWERX3PLUS),0.0D0
      ENDDO
 
      ENDIF

       DO IR=1,RAYCOUNT
        RLIGHTX1T(IR)=RLIGHTX1TPDT(IR)
        RLIGHTX2T(IR)=RLIGHTX2TPDT(IR)
        RLIGHTX3T(IR)=RLIGHTX3TPDT(IR)
      ENDDO

      TIME=TIME+DELTAT
      ENDDO
        RCOUNT=0
        DO IR=1,RAYCOUNT
         RCOUNT=RCOUNT+TFLAG(IR)
         TFLAG(IR)=1.0D0
        ENDDO
        RLIGHTS=RAYCOUNT

        WRITE(*,*)'RAYS HITTING TARGET=',RCOUNT
        WRITE(*,*)'TOTAL RAYS=',RLIGHTS
        WRITE(*,*)'FRACTION OF RAYS HITTING TARGET=',RCOUNT/RLIGHTS

        SUM=0.0D0
        DO I=1,NTARGETS
         SUM=TARGETABSORB(I)+SUM
        ENDDO
        WRITE(*,*)'FRACTION OF POWER ABSORBED=',
     $SUM/(
     $TOTALFACEPOWERX1MINUS*X1MINUSON+
     $TOTALFACEPOWERX1PLUS*X1PLUSON+
     $TOTALFACEPOWERX2MINUS*X2MINUSON+
     $TOTALFACEPOWERX2PLUS*X2PLUSON+
     $TOTALFACEPOWERX3MINUS*X3MINUSON+
     $TOTALFACEPOWERX3PLUS*X3PLUSON)
        WRITE(*,*)'TOTAL NUMBER OF REFLECTIONS=',REF

      STOP
      END
 

      SUBROUTINE GETRAND(IRNUM,RANDNUMBER)

      IMPLICIT NONE
      DOUBLE PRECISION RANDOM
      DOUBLE PRECISION DA,DB,DC,RANDNUMBER
      INTEGER IRNUM
       DA=16807.0D0
       DB=2147483647.0D0
       DC=2147483648.0D0
       IRNUM=DABS(MOD(DA*IRNUM,DB)+0.5D0)
       RANDOM=DFLOAT(IRNUM)/DC
       RANDNUMBER=RANDOM
      RETURN
      END

